# Generated by Django 4.0.3 on 2022-06-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_rename_files_rasm_rasmlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasm',
            name='rasmlar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='commerce.categoriya'),
        ),
    ]
