# Generated by Django 4.0.3 on 2022-06-28 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_rasm_rasmlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('kilogramm', models.IntegerField(max_length=1000, null=True)),
                ('litri', models.IntegerField(max_length=100, null=True)),
                ('soni', models.IntegerField(max_length=1000, null=True)),
                ('narx', models.IntegerField(max_length=100000)),
                ('chegirma_narx', models.CharField(max_length=100000, null=True)),
                ('chegirma_foizi', models.CharField(max_length=10, null=True)),
                ('categoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriya', to='commerce.categoriya')),
            ],
        ),
    ]
