# Generated by Django 4.0.3 on 2022-06-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kilogramm',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='litri',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='narx',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='soni',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
