# Generated by Django 4.0.3 on 2022-06-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_alter_product_categoriya_alter_product_chegirma_narx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoriya',
            new_name='mahsulot',
        ),
    ]
