# Generated by Django 4.0.3 on 2022-06-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_alter_product_kilogramm_alter_product_litri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kilogramm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='litri',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='soni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
