# Generated by Django 4.0.3 on 2022-06-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_alter_product_kilogramm_alter_product_litri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chegirma_foizi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='chegirma_narx',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
