# Generated by Django 4.0.3 on 2022-07-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_alter_product_chegirma_foizi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rasmi',
            old_name='rasmlar',
            new_name='rasmlari',
        ),
    ]
