# Generated by Django 4.0.3 on 2022-07-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_rename_rasmlar_rasmi_rasmlari'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rasmi',
            new_name='ProductRasmi',
        ),
    ]
