# Generated by Django 4.0.3 on 2022-07-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_rename_rasmi_productrasmi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rasm',
            new_name='CategoriyaRasm',
        ),
    ]
