# Generated by Django 4.0.3 on 2022-07-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('phoneNumber', models.IntegerField()),
                ('adderess', models.CharField(max_length=100)),
            ],
        ),
    ]
