# Generated by Django 4.0.3 on 2022-07-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorder',
            old_name='adderess',
            new_name='address',
        ),
    ]
