# Generated by Django 4.0.3 on 2022-07-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_adderess_userorder_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserOrder',
            new_name='User',
        ),
    ]
