# Generated by Django 4.0.3 on 2022-07-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_userorder_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=20)),
                ('litr', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=20)),
                ('summa', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='total',
            field=models.IntegerField(default=1656677351048, max_length=20),
            preserve_default=False,
        ),
    ]
