# Generated by Django 4.0.3 on 2022-07-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_user_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderForUser',
            field=models.ForeignKey(default=1656677351048, on_delete=django.db.models.deletion.CASCADE, related_name='orderForUser', to='order.user'),
            preserve_default=False,
        ),
    ]
