# Generated by Django 4.0.3 on 2022-07-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_orderforuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='litr',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
