# Generated by Django 4.0.3 on 2022-07-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_litr_alter_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ready',
            field=models.CharField(default=1656682136420, max_length=50),
            preserve_default=False,
        ),
    ]
