# Generated by Django 4.0.3 on 2022-07-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_user_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='litr',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='summa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='total',
            field=models.IntegerField(),
        ),
    ]
